# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=80)),
                ('response', models.PositiveSmallIntegerField(default=200)),
                ('status_field', models.BooleanField(default=True)),
            ],
        ),
    ]
