# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='name',
            field=models.CharField(default='unknow', max_length=80),
        ),
    ]
